/* Generated By:JavaCC: Do not edit this line. IndexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IndexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OTHER = 8;
  /** RegularExpression Id. */
  int CHAR1 = 9;
  /** RegularExpression Id. */
  int PHONE_NUM = 21;
  /** RegularExpression Id. */
  int URL = 22;
  /** RegularExpression Id. */
  int NUM_SLASH = 23;
  /** RegularExpression Id. */
  int TEXT = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int NUM = 26;
  /** RegularExpression Id. */
  int PUNC_INTEXT = 27;
  /** RegularExpression Id. */
  int FORMATTED_TEXT = 28;
  /** RegularExpression Id. */
  int FORMATTING = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENTS = 1;
  /** Lexical state. */
  int IN_SCRIPT = 2;
  /** Lexical state. */
  int IN_NOSCRIPT = 3;
  /** Lexical state. */
  int IN_STYLE = 4;
  /** Lexical state. */
  int IN_HTML = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"<!--\"",
    "\"<script\"",
    "\"<noscript\"",
    "\"<style\"",
    "<token of kind 7>",
    "<OTHER>",
    "<CHAR1>",
    "<token of kind 10>",
    "\"-->\"",
    "<token of kind 12>",
    "\"</script>\"",
    "<token of kind 14>",
    "\"</noscript>\"",
    "<token of kind 16>",
    "\"</style>\"",
    "<token of kind 18>",
    "\">\"",
    "<token of kind 20>",
    "<PHONE_NUM>",
    "<URL>",
    "<NUM_SLASH>",
    "<TEXT>",
    "<CHAR>",
    "<NUM>",
    "<PUNC_INTEXT>",
    "<FORMATTED_TEXT>",
    "<FORMATTING>",
  };

}
